imgt_version: "Latest"
DEFAULT_CACHE_SIZE: 1000
loci:
  - A
  - B
  - C
  - DRB1
  - DQA1
  - DQB1
  - DPA1
  - DPB1
hlaProteinOffset:
  A: 0
  B: 0
  C: 0
  DRB1: 0
  DRB3: 0
  DRB4: 0
  DRB5: 0
  DQA1: 0
  DQB1: 0
  DPA1: 0
  DPB1: 0
refseq:
  A: A*01:01:01:01
  B: B*07:02:01:01
  C: C*01:02:01:01
  DRB1: DRB1*01:01:01:01
  DQA1: DQA1*01:01:01:01
  DQB1: DQB1*05:01:01:01
  DPA1: DPA1*01:03:01:01
  DPB1: DPB1*01:01:01:01
first_ten:
  A*01:01:01:01: GSHSMRYFFT
  B*07:02:01:01: GSHSMRYFYT
  C*01:02:01:01: CSHSMKYFFT
  DRB1*01:01:01:01: GDTRPRFLWQ
  DQA1*01:01:01:01: EDIVADHVAS
  DQB1*05:01:01:01: RDSPEDFVYQ
  DPA1*01:03:01:01: IKADHVSTYA
  DPB1*01:01:01:01: RATPENYVYQ
ard_start_pos:
  A: 0
  B: 0
  C: 0
  DRB1: 0
  DQA1: 0
  DQB1: 0
  DPA1: 0
  DPB1: 0
ard_end_pos:
  A: 182
  B: 182
  C: 182
  DRB1: 94
  DQA1: 87
  DQB1: 94
  DPA1: 84
  DPB1: 92
xrd_start_pos:
  A: 0
  B: 0
  C: 0
  DRB1: 0
  DQA1: 0
  DQB1: 0
  DPA1: 0
  DPB1: 0
xrd_end_pos:
  A: 274
  B: 274
  C: 274
  DRB1: 188
  DQA1: 181
  DQB1: 188
  DPA1: 178
  DPB1: 186
expression_chars:
  - N
  - Q
  - L
  - S
gapped_tables:
  - A_gapped
  - B_gapped
  - C_gapped
  - DRB1_gapped
  - DQA1_gapped
  - DQB1_gapped
  - DPA1_gapped
  - DPB1_gapped
ungapped_tables:
  - A_ungapped
  - B_ungapped
  - C_ungapped
  - DRB1_ungapped
  - DQA1_ungapped
  - DQB1_ungapped
  - DPA1_ungapped
  - DPB1_ungapped
completed_tables:
  - A_completed
  - B_completed
  - C_completed
  - DRB1_completed
  - DQA1_completed
  - DQB1_completed
  - DPA1_completed
  - DPB1_completed
incomplete_tables:
  - A_incomplete
  - B_incomplete
  - C_incomplete
  - DRB1_incomplete
  - DQA1_incomplete
  - DQB1_incomplete
  - DPA1_incomplete
  - DPB1_incomplete
extended_tables:
  - A_extended
  - B_extended
  - C_extended
  - DRB1_extended
  - DQA1_extended
  - DQB1_extended
  - DPA1_extended
  - DPB1_extended
position_tables:
  - A_position
  - B_position
  - C_position
  - DRB1_position
  - DQA1_position
  - DQB1_position
  - DPA1_position
  - DPB1_position
